"""create all table

Revision ID: 57951b56149a
Revises: 
Create Date: 2022-06-09 17:23:56.760120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57951b56149a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    op.create_table('points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('childs', sa.ARRAY(sa.String(length=200)), nullable=True),
    sa.Column('longitude', sa.Float()),
    sa.Column('latitude', sa.Float()),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_name'), 'points', ['name'], unique=True)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.String(length=255)),
    sa.Column('points', sa.ARRAY(sa.String(length=200)), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    )
    op.create_index(op.f('ix_routes_name'), 'routes', ['name'], unique=True)
    op.execute(
        """
        INSERT INTO users(id, name, email, password)
        VALUES 
        (1, 'user1', 'test1@gmail.com', '$argon2id$v=19$m=65536,t=3,p=4$6BmjA4j5eVMnp9gRL/8nGA$7A7dBk+phUmdChoUKOAvdl5KWHXTwdbItRAFwb4njsY'),
        (2, 'user2', 'test2@gmail.com', '$argon2id$v=19$m=65536,t=3,p=4$f8/BZAiVTrENxUsbHmtcaw$HCd26aITBDBNu21XuMbdaJo0GJE+cc9TWk/v1EzMLyA'),
        (3, 'user3', 'test3@gmail.com', '$argon2id$v=19$m=65536,t=3,p=4$Bv6GidaAjV6j64T9gxGRpA$4NaPGKkQt5/qDbqkovUvVVpXriKZdf3g/I4UK+Qu4QI');
        """
    )
    op.execute(
        """
        INSERT INTO points(id, name, childs, longitude, latitude )
        VALUES 
            (1,'Almaty', ARRAY[2, 3], 1.1, 1.2),
            (2,'Nur-sultan', ARRAY[1, 5], 1.3, 1.4),
            (3,'Shimkent', ARRAY[1, 4], 1.5, 1.6),
            (4,'Aktobe', ARRAY[6, 7], 1.7, 1.8),
            (5,'Pavlodar', ARRAY[2], 1.9, 1.10),
            (6,'Taraz', ARRAY[4], 1.11, 1.12),
            (7,'Atyrau', ARRAY[4], 1.13, 1.14);
        
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_routes_user_id'), table_name='user_routes')
    op.drop_index(op.f('ix_user_routes_route_name'), table_name='user_routes')
    op.drop_table('user_routes')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_routes_name'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_points_name'), table_name='points')
    op.drop_table('points')
    # ### end Alembic commands ###
